### ISSUE TITLE
Include releases in tags

### ISSUE THREAD

**Issue by dtiersch** [whispeer/app#110]
It would be nice to have the releases in the same repository as the app itself. For this Github offers the possibility to add binary packages directly to releases/tags. See [kebase releases](https://github.com/keybase/client/releases) as a reference.

**Comment by Nilos** [comment]
I included the latest release: https://github.com/whispeer/app/releases/tag/release%2F0.0.6

**Comment by xyng** [comment]
It seems like this issue has been resolved. Closing!
